import type { VocabularyFacetId } from "./types.ts";
import { defaultTuple, slotDefault } from "./helpers.ts";

export const DEFAULT_MAX_CANDIDATES_PER_FACET = 512;
export const DEFAULT_MAX_CANDIDATES_PER_PROMPT = 48;
export const CANDIDATE_EXAMPLE_LIMIT = 64;
export const SEMANTIC_EVIDENCE_LIMIT = 64;
export const VOCABULARY_PROMPT_CHAR_BUDGET = 3_200_000;
export const VOCABULARY_CURATION_TIMEOUT_MS = 1_200_000;
export const PROMPT_SEMANTIC_EVIDENCE_LIMITS = [64, 48, 40, 32, 24, 16, 12, 8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_SEMANTIC_EVIDENCE_LIMITS = [12, 8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_EVIDENCE_LIMIT = 16;
export const SEMANTIC_TEXT_PROMPT_LIMIT = 1_200;
export const RUNTIME_TOOLTIP_REPEAT_BOILERPLATE_THRESHOLD = 250;
export const GENERIC_TOKENS = new Set([
  "misc",
  "miscellaneous",
  "general",
  "generic",
  "materials",
  "material",
  "components",
  "component",
  "items",
  "blocks",
  "things",
  "stuff",
  "crafting",
  "crafting_shaped",
  "crafting_shapeless",
  "recipes",
  "recipe",
  "machine",
  "machines",
]);

export const MOD_SUBSYSTEM_STOP_TOKENS = new Set([
  ...GENERIC_TOKENS,
  "armor",
  "armour",
  "block",
  "bucket",
  "clothing",
  "component",
  "components",
  "dust",
  "equipment",
  "gear",
  "ingot",
  "item",
  "material",
  "nugget",
  "ore",
  "plate",
  "resource",
  "resources",
  "rod",
  "screw",
  "suit",
  "tool",
  "tools",
  "weapon",
  "weapons",
  "wire",
]);

export const MOD_SUBSYSTEM_SIGNAL_TOKENS = new Set([
  "assembler",
  "automation",
  "battery",
  "batteries",
  "belt",
  "bus",
  "buses",
  "cable",
  "cables",
  "cell",
  "cells",
  "charger",
  "chargers",
  "chute",
  "chutes",
  "cogwheel",
  "contraption",
  "conveyor",
  "cover",
  "crafter",
  "deployer",
  "duct",
  "energy",
  "engine",
  "export",
  "fan",
  "fission",
  "fluid",
  "generator",
  "hatch",
  "interface",
  "kinetic",
  "kinetics",
  "logistics",
  "mechanical_power",
  "power",
  "multiblock",
  "network",
  "oxygen",
  "package",
  "pipe",
  "pipes",
  "pump",
  "rail",
  "reactor",
  "rocket",
  "schematic",
  "shaft",
  "storage",
  "tank",
  "terminal",
  "track",
  "train",
  "trains",
  "transport",
  "turbine",
]);

export const MOD_SUBSYSTEM_CANONICAL_TOKENS = new Map([
  ["batteries", "battery"],
  ["buses", "bus"],
  ["cables", "cable"],
  ["cells", "cell"],
  ["chargers", "charger"],
  ["chutes", "chute"],
  ["kinetic", "kinetics"],
  ["pipes", "pipe"],
  ["trains", "train"],
]);

export const ORGANIZATION_GROUP_STOP_TOKENS = new Set([
  "anvil",
  "anvils",
  "barrel",
  "barrels",
  "blasting",
  "compacting",
  "crafting",
  "cutting",
  "default",
  "deploying",
  "filling",
  "milling",
  "mixing",
  "oven",
  "ovens",
  "pot",
  "pots",
  "pressing",
  "quern",
  "querns",
  "smelting",
  "stonecutting",
]);

export const VOLTAGE_COMPONENT_TOKENS = new Set([
  "battery",
  "cable",
  "circuit",
  "component",
  "components",
  "conveyor",
  "cover",
  "electric",
  "emitter",
  "field",
  "generator",
  "hatch",
  "hull",
  "motor",
  "piston",
  "pump",
  "robot",
  "sensor",
]);

export const VOLTAGE_TIERS = ["ulv", "lv", "mv", "hv", "ev", "iv", "luv", "zpm", "uv", "uhv"] as const;

export const UNIVERSAL_DEFAULTS: Record<string, Array<{ id: string; label: string; description?: string; aliases?: string[] }>> = {
  activity: ([
    ["slot:mining", "Mining"],
    ["slot:exploration", "Exploration"],
    ["slot:cooking", "Cooking", "Food preparation, cooking, meals, and drink work.", ["food prep"]],
    ["slot:building", "Building"],
    ["slot:decorating", "Decorating"],
    ["slot:combat", "Combat"],
    ["slot:farming", "Farming"],
    ["slot:redstone", "Redstone"],
    ["slot:automation", "Automation"],
    ["slot:logistics", "Logistics"],
    ["slot:storage_management", "Storage Management"],
    ["slot:brewing", "Brewing"],
    ["slot:enchanting", "Enchanting"],
    ["slot:magic", "Magic"],
    ["slot:power_generation", "Power Generation"],
    ["slot:transportation", "Transportation"],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
  food_category: [
    "fruit",
    "vegetable",
    "grain",
    "flour",
    "dough",
    "bread",
    "meat",
    "fish",
    "dairy",
    "cheese",
    "egg",
    "spice",
    "sweetener",
    "fat_oil",
    "sauce",
    "prepared_meal",
    "preserve",
    "drink",
    "bowl",
  ].map(slotDefault),
  food_use: [
    "eat_now",
    "ingredient",
    "meal_component",
    "drink",
    "preserve",
    "animal_feed",
    "buff_food",
    "cooking_fat",
    "sweetener",
    "spice",
  ].map(slotDefault),
  preparation_state: [
    "raw",
    "cooked",
    "dried",
    "salted",
    "pickled",
    "fermented",
    "curdled",
    "flour",
    "dough",
    "preserved",
    "unsealed",
    "sealed",
  ].map(slotDefault),
  material_process_stage: [
    "ore",
    "crushed_ore",
    "purified_ore",
    "dust",
    "tiny_dust",
    "nugget",
    "ingot",
    "double_ingot",
    "sheet",
    "double_sheet",
    "rod",
    "plate",
    "bloom",
    "billet",
    "molten",
    "alloy",
    "mold",
  ].map(slotDefault),
  stock_profile: [
    "bulk",
    "small_batch",
    "singleton",
    "tooling",
    "reserve",
    "display",
    "overflow",
  ].map(slotDefault),
  container_state: [
    "empty_container",
    "filled_container",
    "fluid_container",
    "gas_container",
    "energy_container",
    "reusable_mold",
    "single_use_mold",
    "pattern_template",
    "has_contents",
    "accepts_contents",
  ].map(slotDefault),
  equipment_effect: [
    "night_vision",
    "water_breathing",
    "oxygen_supply",
    "flight",
    "step_assist",
    "speed_boost",
    "reach_boost",
    "tool_mode",
  ].map(slotDefault),
  protection_context: [
    "heat",
    "cold",
    "radiation",
    "vacuum",
    "pressure",
    "fire",
    "poison",
    "fall",
    "magic",
  ].map(slotDefault),
  loadout_context: [
    "mining_run",
    "cave_run",
    "farming_run",
    "building_project",
    "exploration_trip",
    "combat_trip",
    "base_maintenance",
    "machine_setup",
  ].map(slotDefault),
  use_affordance: [
    "place",
    "open",
    "eat",
    "drink",
    "equip",
    "fuel",
    "repair",
    "configure",
    "cast",
    "fill",
    "empty",
    "preserve",
    "harvest",
    "scan",
    "launch",
  ].map(slotDefault),
};

export const FACET_POLICIES: Partial<Record<VocabularyFacetId, string>> = {
  activity: "Broad player activities. Prefer universal slot:* defaults. Reject recipe-internal verbs.",
  workflow: "Player-facing process/task contexts. Use recipe, guide, quest, or advancement evidence. Reject catch-alls and one-off tutorial/advancement titles.",
  workflow_role: "Scoped role values only, formatted as <workflow>#<role>. Parent must be an accepted workflow candidate.",
  used_at: "Player-facing station, machine, tool, or surface. Preserve raw recipe type evidence separately.",
  progression_stage: "Pack/mod progression gates, tiers, ages, voltages, dimensions. Conservative; reject item/product topics and one-off advancements.",
  organization_group: "Direct wall-home candidate: human storage/section groupings, not stations or recipe workflows.",
  mod_subsystem: "Identity-oriented mod subsystem. Do not assign from recipe participation alone.",
};

export const ROLE_TOKENS = ["input", "output"] as const;
export const ORGANIZATION_GROUP_PREFIX_STOP_TOKENS = new Set([
  "block",
  "blocks",
  "item",
  "items",
  "tag",
  "tags",
  "whitelisted",
  "blacklisted",
  "mineable",
  "needs",
  "incorrect",
  "replaceable",
  "replacements",
  "runtime",
  "generated",
  "compat",
  "completes",
]);

export const ORGANIZATION_GROUP_SUFFIX_STOP_TOKENS = new Set([
  "replaceable",
  "replaceables",
  "whitelisted",
  "blacklisted",
  "pickup",
  "tutorial",
]);
