import type { VocabularyFacetId } from "./types.ts";
import { defaultTuple } from "./helpers.ts";

export const DEFAULT_MAX_CANDIDATES_PER_FACET = 5_000;
export const DEFAULT_COMBINED_MAX_CANDIDATES_PER_FACET = 256;
export const CANDIDATE_EXAMPLE_LIMIT = 64;
export const SEMANTIC_EVIDENCE_LIMIT = 64;
export const VOCABULARY_PROMPT_CHAR_BUDGET = 3_200_000;
export const VOCABULARY_CURATION_TIMEOUT_MS = 1_200_000;
export const PROMPT_SEMANTIC_EVIDENCE_LIMITS = [16, 12, 8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_SEMANTIC_EVIDENCE_LIMITS = [8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_EVIDENCE_LIMIT = 16;
export const SEMANTIC_TEXT_PROMPT_LIMIT = 1_200;
export const RUNTIME_TOOLTIP_REPEAT_BOILERPLATE_THRESHOLD = 250;
export const GENERIC_TOKENS = new Set([
  "misc",
  "miscellaneous",
  "general",
  "generic",
  "materials",
  "material",
  "components",
  "component",
  "items",
  "blocks",
  "things",
  "stuff",
  "crafting",
  "crafting_shaped",
  "crafting_shapeless",
  "recipes",
  "recipe",
  "machine",
  "machines",
]);

export const MOD_SUBSYSTEM_STOP_TOKENS = new Set([
  ...GENERIC_TOKENS,
  "armor",
  "armour",
  "block",
  "bucket",
  "clothing",
  "component",
  "components",
  "dust",
  "equipment",
  "gear",
  "ingot",
  "item",
  "material",
  "nugget",
  "ore",
  "plate",
  "resource",
  "resources",
  "rod",
  "screw",
  "suit",
  "tool",
  "tools",
  "weapon",
  "weapons",
  "wire",
]);

export const MOD_SUBSYSTEM_SIGNAL_TOKENS = new Set([
  "assembler",
  "automation",
  "battery",
  "batteries",
  "belt",
  "bus",
  "buses",
  "cable",
  "cables",
  "cell",
  "cells",
  "charger",
  "chargers",
  "chute",
  "chutes",
  "cogwheel",
  "contraption",
  "conveyor",
  "cover",
  "crafter",
  "deployer",
  "duct",
  "energy",
  "engine",
  "export",
  "fan",
  "fission",
  "fluid",
  "generator",
  "hatch",
  "interface",
  "kinetic",
  "kinetics",
  "logistics",
  "mechanical_power",
  "power",
  "multiblock",
  "network",
  "oxygen",
  "package",
  "pipe",
  "pipes",
  "pump",
  "rail",
  "reactor",
  "rocket",
  "schematic",
  "shaft",
  "storage",
  "tank",
  "terminal",
  "track",
  "train",
  "trains",
  "transport",
  "turbine",
]);

export const MOD_SUBSYSTEM_CANONICAL_TOKENS = new Map([
  ["batteries", "battery"],
  ["buses", "bus"],
  ["cables", "cable"],
  ["cells", "cell"],
  ["chargers", "charger"],
  ["chutes", "chute"],
  ["kinetic", "kinetics"],
  ["pipes", "pipe"],
  ["trains", "train"],
]);

export const ORGANIZATION_GROUP_STOP_TOKENS = new Set([
  "anvil",
  "anvils",
  "barrel",
  "barrels",
  "blasting",
  "compacting",
  "crafting",
  "cutting",
  "default",
  "deploying",
  "filling",
  "milling",
  "mixing",
  "oven",
  "ovens",
  "pot",
  "pots",
  "pressing",
  "quern",
  "querns",
  "smelting",
  "stonecutting",
]);

export const BUILT_IN_VOCABULARY_SEEDS: Record<string, Array<{ id: string; label: string; description?: string; aliases?: string[] }>> = {
  organization_group: ([
    ["food", "Food", "Food, meals, edible ingredients, and drink items."],
    ["tools", "Tools", "Reusable handheld tools and utility implements."],
    ["weapons", "Weapons", "Weapons, ammunition, and combat attack items."],
    ["armor", "Armor", "Wearable protection and armor pieces."],
    ["lighting", "Lighting", "Torches, lanterns, lamps, candles, and light-emitting blocks."],
    ["ores_raw_stock", "Ores & Raw Stock", "Ore blocks, raw ores, crushed ores, and mine-run resource stock.", ["raw ore"]],
    ["metal_stock", "Metal Stock", "Ingots, nuggets, plates, rods, wires, bolts, screws, foils, and similar metal stock.", ["ingots", "plates"]],
    ["gems_crystals", "Gems & Crystals", "Gems, crystals, mineral gemstones, and similar cut or crystalline stock.", ["gems"]],
    ["dusts_powders", "Dusts & Powders", "Dusts, powders, piles, and powdered processing outputs.", ["dusts"]],
    ["wood", "Wood", "Logs, planks, boards, lumber, sticks, beams, and close stock-wood siblings."],
    ["seeds", "Seeds", "Seed stock and plantable crop starts."],
    ["crops", "Crops", "Harvested crop produce, grains, vegetables, and fruit."],
    ["plants", "Plants", "Saplings, flowers, leaves, grass, mushrooms, and non-crop botanical stock."],
    ["ceramics_molds", "Ceramics & Molds", "Clay, ceramic, brick, pottery, and mold stock.", ["pottery", "molds"]],
    ["organic_materials", "Organic Materials", "Leather, hide, wool, string, fiber, straw, bone, slime, wax, and animal/plant organic stock."],
    ["storage", "Storage", "Chests, barrels, crates, sacks, bags, backpacks, drawers, tanks, and other containers.", ["item containers"]],
    ["stairs", "Stairs", "Stair-shaped building variants."],
    ["slabs", "Slabs", "Slab-shaped building variants."],
    ["walls", "Walls", "Wall-shaped building variants."],
    ["doors", "Doors", "Doors, trapdoors, and gates."],
    ["fences", "Fences", "Fences and fence-like boundary pieces."],
    ["windows", "Windows", "Panes, bars, windows, and window-like blocks."],
    ["building_blocks", "Building Blocks", "General structural blocks and ordinary building materials."],
    ["decoration", "Decoration", "Decorative blocks, ornaments, signs, banners, carpets, and visual flourish."],
    ["natural", "Natural", "Dirt, sand, gravel, stone, rocks, soil, mud, and other natural terrain stock."],
    ["workbenches", "Workbenches", "Crafting stations, tables, benches, and placed work surfaces."],
    ["mechanisms", "Mechanisms", "Machines, mechanisms, motors, gears, shafts, belts, pipes, and automation parts."],
    ["redstone", "Redstone", "Redstone, signal components, levers, repeaters, comparators, buttons, and pressure plates."],
    ["upgrades", "Upgrades", "Upgrades, modules, augments, and installable improvement items."],
    ["transport", "Transport", "Rails, tracks, carts, boats, rockets, trains, and movement infrastructure."],
    ["utility", "Utility", "Buckets, bottles, maps, ropes, ladders, and other general utility items."],
    ["curiosities", "Curiosities", "Trophies, relics, discs, spawn eggs, curios, and display oddities."],
    ["materials", "Materials", "Last-resort generic crafting stock when no narrower stock group fits; avoid when a better default or custom group applies."],
    ["miscellaneous", "Miscellaneous", "Last-resort home for items that do not fit any other broad player storage section.", ["misc"]],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
};

export const FACET_POLICIES: Partial<Record<VocabularyFacetId, string>> = {
  role: "Primary player-recognized item role/home type. Synthesize a compact role vocabulary from the pack's actual item universe. Roles should be broad, stable inventory concepts, not mod namespaces, recipe participation, material families, or one-off item names.",
  material_family: "Primary material or substance families. Synthesize stable reusable material tokens from actual item ids, names, tags, recipes, and text. Normalize obvious synonyms across the pack. Do not create one value per item, color variant, host-rock/geology detail, or decorative style unless players would treat it as a real material family.",
  material_secondary: "Secondary material families for composite items. Use the same material vocabulary style as material_family, but only for secondary substances players would notice or search for. Do not duplicate the primary material or emit recipe inputs that are not part of the item.",
  form: "Visible or inventory-recognized physical form factor. Synthesize reusable shape/form values from item names, tags, models, components, and pack prose. Do not use purpose/home roles, station names, material names, or recipe steps as forms.",
  tier: "Progression or capability tiers for tools, armor, machines, materials, or pack systems. Synthesize recurring tier labels from evidence. Do not use rarity, organization groups, one-off item names, or tutorial chapter names as tiers.",
  required_tool: "Player-recognized harvest/tool classes required by blocks or interactions. Synthesize reusable tool class values from tags, components, text, and pack conventions. Do not limit values to vanilla tools when the pack adds hammers, saws, knives, wrenches, or similar tools.",
  required_tool_tier: "Harvest/tool requirement tiers. Synthesize only tiers that recur in tool or block requirement evidence. Prefer concise pack/mod tier tokens and avoid assuming vanilla-only tiers when the pack defines more.",
  equip_slot: "Wear/equip slots and attachment locations. Synthesize reusable slot values from components, tooltips, Curios/accessory evidence, mounts, vehicles, and pack text. Do not assume vanilla armor slots are complete.",
  activity: "Broad player activities. Synthesize concise reusable activity values from the pack's actual item universe and semantic evidence. Reject recipe-internal verbs.",
  origin: "World, dimension, structure, biome, source, or acquisition contexts where items come from. Synthesize reusable player-facing origins from positive evidence. Do not fill generic crafted-only or absent-loot guesses for ordinary items.",
  storage_categories: "Special container slot kinds, storage media, or storage behavior. Synthesize reusable storage categories only when they change how a player stores, fills, opens, or reasons about the item.",
  spawn_interaction: "Mob spawning, movement, and survival interactions. Synthesize reusable mechanics such as spawn blocking, attraction, repulsion, damage, launch, transport, or pack-specific spawn systems.",
  combat_bonus: "Specific combat bonuses, target families, bosses, status inflictions, or combat mechanics beyond base damage. Synthesize reusable values only when the item evidence supports the mechanic.",
  environmental_property: "World physics and ambient interactions such as fire, fluids, piston behavior, gravity, noise, mob reactions, movement, hazards, or pack-specific environmental mechanics.",
  transport_medium: "Mediums moved, carried, transported, or transmitted by logistics and automation items. Synthesize pack-shaped media such as item, fluid, gas, energy, pressure, heat, data, mana, oxygen, radiation, player, or mob when evidence supports them.",
  workflow: "Player-facing process/task contexts. Use recipe, guide, quest, or advancement evidence. Reject catch-alls and one-off tutorial/advancement titles.",
  workflow_role: "Scoped role values only, formatted as <workflow>#<role>. Parent must be a usable workflow value.",
  used_at: "Player-facing station, machine, tool, or surface. Preserve raw recipe type evidence separately.",
  food_category: "Food families and ingredient types. Synthesize recurring categories from actual foods, ingredients, tags, recipes, and prose. Avoid individual dishes, crops, or preparation states unless the pack uses them as reusable categories.",
  food_use: "Why a player cares about the item in food contexts. Synthesize reusable uses such as feeding, preserving, nutrition, hydration, or pack-specific meal mechanics. Do not duplicate food_category or preparation_state.",
  preparation_state: "Food or material preparation state. Synthesize reusable states like smoked, brined, canned, ground, or unsealed when they recur across items. Do not use station names or one-off recipe steps.",
  material_process_stage: "Reusable material-processing form or stage. Synthesize broad forms/stages from the pack's actual item universe, tags, recipes, and prose. Do not rely on built-in pack-specific defaults; do not split by individual material, machine, or organization-home concern.",
  stock_profile: "How a player stocks, carries, or treats item quantity. Synthesize reusable inventory-behavior profiles. Do not use item type labels, material families, or storage section names.",
  container_state: "Reusable container/vessel state or behavior. Synthesize broad states such as charged, sealed, contaminated, patterned, or accepts-a-content-kind. Do not encode exact contents or block/item family.",
  equipment_effect: "Player-visible effect granted by carrying, wearing, or using equipment. Synthesize recurring effects, modes, or capabilities. Do not encode armor material, tier, or hazard protection.",
  protection_context: "Hazard or environment an item protects against or is designed for. Synthesize recurring pack-specific hazards or environments. Do not duplicate equipment_effect or generic combat role.",
  progression_stage: "Pack/mod progression gates, tiers, ages, voltages, dimensions. Conservative; reject item/product topics and one-off advancements.",
  loadout_context: "Trip, kit, or task context where a player would pack the item. Synthesize recurring expeditions, dimensions, or jobs. Do not create one-off recipe or station task labels.",
  use_affordance: "Direct interaction verbs a player can do with the item. Synthesize reusable verbs or affordances. Do not use recipe membership, workflow names, station names, or item families.",
  organization_group: "Direct wall-home value. Accept only scarce, broad sections a human player would maintain primarily by item type/role, with use or state as secondary; not stations, recipe workflows, mod names, narrow material properties, or query filters.",
  mod_subsystem: "Identity-oriented mod subsystem. Do not assign from recipe participation alone.",
  produces_effect: "Status effects an item grants, applies, clears, or delivers. Use namespace-qualified effect ids when evidence supports them. Prefer exact component/tooltip/guide evidence; do not invent effect ids from vague flavor text.",
  multiblock_component_of: "Named multiblocks or built structures where this item is an actual required component. Use namespace-qualified multiblock ids derived from pack/mod evidence. Do not use generic machines, recipes, or decorative structure names.",
  multiblock_role: "Reusable roles an item can play inside named multiblocks or built structures. Synthesize roles such as controller, casing, port, valve, hatch, frame, coil, lens, or pack-specific equivalents only when multiblock evidence supports them.",
  biome: "Specific biomes where this item is naturally found or strongly biome-endemic. Use namespace-qualified biome ids when evidence supports them. Do not emit broad dimensions, origin buckets, or decorative biome themes without actual sourcing evidence.",
};

export const ROLE_TOKENS = ["input", "output"] as const;
export const ORGANIZATION_GROUP_PREFIX_STOP_TOKENS = new Set([
  "block",
  "blocks",
  "item",
  "items",
  "tag",
  "tags",
  "whitelisted",
  "blacklisted",
  "mineable",
  "needs",
  "incorrect",
  "replaceable",
  "replacements",
  "runtime",
  "generated",
  "compat",
  "completes",
]);

export const ORGANIZATION_GROUP_SUFFIX_STOP_TOKENS = new Set([
  "replaceable",
  "replaceables",
  "whitelisted",
  "blacklisted",
  "pickup",
  "tutorial",
]);
