import type { VocabularyFacetId } from "./types.ts";
import { defaultTuple, slotDefault } from "./helpers.ts";

export const DEFAULT_MAX_CANDIDATES_PER_FACET = 5_000;
export const CANDIDATE_EXAMPLE_LIMIT = 64;
export const SEMANTIC_EVIDENCE_LIMIT = 64;
export const VOCABULARY_PROMPT_CHAR_BUDGET = 3_200_000;
export const VOCABULARY_CURATION_TIMEOUT_MS = 1_200_000;
export const PROMPT_SEMANTIC_EVIDENCE_LIMITS = [16, 12, 8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_SEMANTIC_EVIDENCE_LIMITS = [8, 4, 2, 1, 0] as const;
export const MOD_SUBSYSTEM_PROMPT_EVIDENCE_LIMIT = 16;
export const SEMANTIC_TEXT_PROMPT_LIMIT = 1_200;
export const RUNTIME_TOOLTIP_REPEAT_BOILERPLATE_THRESHOLD = 250;
export const GENERIC_TOKENS = new Set([
  "misc",
  "miscellaneous",
  "general",
  "generic",
  "materials",
  "material",
  "components",
  "component",
  "items",
  "blocks",
  "things",
  "stuff",
  "crafting",
  "crafting_shaped",
  "crafting_shapeless",
  "recipes",
  "recipe",
  "machine",
  "machines",
]);

export const MOD_SUBSYSTEM_STOP_TOKENS = new Set([
  ...GENERIC_TOKENS,
  "armor",
  "armour",
  "block",
  "bucket",
  "clothing",
  "component",
  "components",
  "dust",
  "equipment",
  "gear",
  "ingot",
  "item",
  "material",
  "nugget",
  "ore",
  "plate",
  "resource",
  "resources",
  "rod",
  "screw",
  "suit",
  "tool",
  "tools",
  "weapon",
  "weapons",
  "wire",
]);

export const MOD_SUBSYSTEM_SIGNAL_TOKENS = new Set([
  "assembler",
  "automation",
  "battery",
  "batteries",
  "belt",
  "bus",
  "buses",
  "cable",
  "cables",
  "cell",
  "cells",
  "charger",
  "chargers",
  "chute",
  "chutes",
  "cogwheel",
  "contraption",
  "conveyor",
  "cover",
  "crafter",
  "deployer",
  "duct",
  "energy",
  "engine",
  "export",
  "fan",
  "fission",
  "fluid",
  "generator",
  "hatch",
  "interface",
  "kinetic",
  "kinetics",
  "logistics",
  "mechanical_power",
  "power",
  "multiblock",
  "network",
  "oxygen",
  "package",
  "pipe",
  "pipes",
  "pump",
  "rail",
  "reactor",
  "rocket",
  "schematic",
  "shaft",
  "storage",
  "tank",
  "terminal",
  "track",
  "train",
  "trains",
  "transport",
  "turbine",
]);

export const MOD_SUBSYSTEM_CANONICAL_TOKENS = new Map([
  ["batteries", "battery"],
  ["buses", "bus"],
  ["cables", "cable"],
  ["cells", "cell"],
  ["chargers", "charger"],
  ["chutes", "chute"],
  ["kinetic", "kinetics"],
  ["pipes", "pipe"],
  ["trains", "train"],
]);

export const ORGANIZATION_GROUP_STOP_TOKENS = new Set([
  "anvil",
  "anvils",
  "barrel",
  "barrels",
  "blasting",
  "compacting",
  "crafting",
  "cutting",
  "default",
  "deploying",
  "filling",
  "milling",
  "mixing",
  "oven",
  "ovens",
  "pot",
  "pots",
  "pressing",
  "quern",
  "querns",
  "smelting",
  "stonecutting",
]);

export const UNIVERSAL_DEFAULTS: Record<string, Array<{ id: string; label: string; description?: string; aliases?: string[] }>> = {
  organization_group: ([
    ["slot:food", "Food", "Food, meals, edible ingredients, and drink items."],
    ["slot:tools", "Tools", "Reusable handheld tools and utility implements."],
    ["slot:weapons", "Weapons", "Weapons, ammunition, and combat attack items."],
    ["slot:armor", "Armor", "Wearable protection and armor pieces."],
    ["slot:lighting", "Lighting", "Torches, lanterns, lamps, candles, and light-emitting blocks."],
    ["slot:ores_raw_stock", "Ores & Raw Stock", "Ore blocks, raw ores, crushed ores, and mine-run resource stock.", ["raw ore"]],
    ["slot:metal_stock", "Metal Stock", "Ingots, nuggets, plates, rods, wires, bolts, screws, foils, and similar metal stock.", ["ingots", "plates"]],
    ["slot:gems_crystals", "Gems & Crystals", "Gems, crystals, mineral gemstones, and similar cut or crystalline stock.", ["gems"]],
    ["slot:dusts_powders", "Dusts & Powders", "Dusts, powders, piles, and powdered processing outputs.", ["dusts"]],
    ["slot:wood", "Wood", "Logs, planks, boards, lumber, sticks, beams, and close stock-wood siblings."],
    ["slot:seeds", "Seeds", "Seed stock and plantable crop starts."],
    ["slot:crops", "Crops", "Harvested crop produce, grains, vegetables, and fruit."],
    ["slot:plants", "Plants", "Saplings, flowers, leaves, grass, mushrooms, and non-crop botanical stock."],
    ["slot:ceramics_molds", "Ceramics & Molds", "Clay, ceramic, brick, pottery, and mold stock.", ["pottery", "molds"]],
    ["slot:organic_materials", "Organic Materials", "Leather, hide, wool, string, fiber, straw, bone, slime, wax, and animal/plant organic stock."],
    ["slot:storage", "Storage", "Chests, barrels, crates, sacks, bags, backpacks, drawers, tanks, and other containers.", ["item containers"]],
    ["slot:stairs", "Stairs", "Stair-shaped building variants."],
    ["slot:slabs", "Slabs", "Slab-shaped building variants."],
    ["slot:walls", "Walls", "Wall-shaped building variants."],
    ["slot:doors", "Doors", "Doors, trapdoors, and gates."],
    ["slot:fences", "Fences", "Fences and fence-like boundary pieces."],
    ["slot:windows", "Windows", "Panes, bars, windows, and window-like blocks."],
    ["slot:building_blocks", "Building Blocks", "General structural blocks and ordinary building materials."],
    ["slot:decoration", "Decoration", "Decorative blocks, ornaments, signs, banners, carpets, and visual flourish."],
    ["slot:natural", "Natural", "Dirt, sand, gravel, stone, rocks, soil, mud, and other natural terrain stock."],
    ["slot:workbenches", "Workbenches", "Crafting stations, tables, benches, and placed work surfaces."],
    ["slot:mechanisms", "Mechanisms", "Machines, mechanisms, motors, gears, shafts, belts, pipes, and automation parts."],
    ["slot:redstone", "Redstone", "Redstone, signal components, levers, repeaters, comparators, buttons, and pressure plates."],
    ["slot:upgrades", "Upgrades", "Upgrades, modules, augments, and installable improvement items."],
    ["slot:transport", "Transport", "Rails, tracks, carts, boats, rockets, trains, and movement infrastructure."],
    ["slot:utility", "Utility", "Buckets, bottles, maps, ropes, ladders, and other general utility items."],
    ["slot:curiosities", "Curiosities", "Trophies, relics, discs, spawn eggs, curios, and display oddities."],
    ["slot:materials", "Materials", "Last-resort generic crafting stock when no narrower stock group fits; avoid when a better default or custom group applies."],
    ["slot:miscellaneous", "Miscellaneous", "Last-resort home for items that do not fit any other broad player storage section.", ["misc"]],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
  activity: ([
    ["slot:mining", "Mining"],
    ["slot:exploration", "Exploration"],
    ["slot:cooking", "Cooking", "Food preparation, cooking, meals, and drink work.", ["food prep"]],
    ["slot:building", "Building"],
    ["slot:decorating", "Decorating"],
    ["slot:combat", "Combat"],
    ["slot:farming", "Farming"],
    ["slot:redstone", "Redstone"],
    ["slot:automation", "Automation"],
    ["slot:logistics", "Logistics"],
    ["slot:storage_management", "Storage Management"],
    ["slot:brewing", "Brewing"],
    ["slot:enchanting", "Enchanting"],
    ["slot:magic", "Magic"],
    ["slot:power_generation", "Power Generation"],
    ["slot:transportation", "Transportation"],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
  food_category: [
    "fruit",
    "vegetable",
    "grain",
    "flour",
    "dough",
    "bread",
    "meat",
    "fish",
    "dairy",
    "cheese",
    "egg",
    "spice",
    "sweetener",
    "fat_oil",
    "sauce",
    "prepared_meal",
    "preserve",
    "drink",
    "bowl",
  ].map(slotDefault),
  food_use: ([
    ["slot:eat_now", "Eat Now"],
    [
      "slot:ingredient",
      "Ingredient",
      "Food item used as an input in cooking, mixing, or other food preparation.",
      ["cooking ingredient"],
    ],
    ["slot:meal_component", "Meal Component"],
    ["slot:drink", "Drink"],
    ["slot:preserve", "Preserve"],
    ["slot:animal_feed", "Animal Feed"],
    ["slot:buff_food", "Buff Food"],
    ["slot:cooking_fat", "Cooking Fat"],
    ["slot:sweetener", "Sweetener"],
    ["slot:spice", "Spice"],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
  preparation_state: [
    "raw",
    "cooked",
    "dried",
    "salted",
    "pickled",
    "fermented",
    "curdled",
    "flour",
    "dough",
    "preserved",
    "unsealed",
    "sealed",
  ].map(slotDefault),
  material_process_stage: [
    "ore",
    "crushed_ore",
    "purified_ore",
    "dust",
    "tiny_dust",
    "nugget",
    "ingot",
    "double_ingot",
    "sheet",
    "double_sheet",
    "rod",
    "plate",
    "bloom",
    "billet",
    "molten",
    "alloy",
    "mold",
  ].map(slotDefault),
  stock_profile: [
    "bulk",
    "small_batch",
    "singleton",
    "tooling",
    "reserve",
    "display",
    "overflow",
  ].map(slotDefault),
  container_state: ([
    [
      "slot:empty_container",
      "Empty Container",
      "Container or vessel currently holding no contents and ready to fill.",
      ["empty"],
    ],
    ["slot:filled_container", "Filled Container", "Container or vessel currently holding contents.", ["filled"]],
    [
      "slot:fluid_container",
      "Fluid Container",
      "Container intended for liquids, whether empty or filled.",
      ["fluid filled", "liquid container"],
    ],
    ["slot:gas_container", "Gas Container", "Container intended for gases, whether empty or filled.", ["gas filled"]],
    [
      "slot:energy_container",
      "Energy Container",
      "Item that stores charge or energy, such as a battery or energy cell.",
      ["charged", "energy charged"],
    ],
    ["slot:reusable_mold", "Reusable Mold"],
    ["slot:single_use_mold", "Single Use Mold"],
    [
      "slot:pattern_template",
      "Pattern Template",
      "Template, encoded pattern, or shape pattern used by automated crafting or machines.",
    ],
    ["slot:has_contents", "Has Contents"],
    ["slot:accepts_contents", "Accepts Contents"],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
  equipment_effect: [
    "night_vision",
    "water_breathing",
    "oxygen_supply",
    "flight",
    "step_assist",
    "speed_boost",
    "reach_boost",
    "tool_mode",
  ].map(slotDefault),
  protection_context: [
    "heat",
    "cold",
    "radiation",
    "vacuum",
    "pressure",
    "fire",
    "poison",
    "fall",
    "magic",
  ].map(slotDefault),
  loadout_context: [
    "mining_run",
    "cave_run",
    "farming_run",
    "building_project",
    "exploration_trip",
    "combat_trip",
    "base_maintenance",
    "machine_setup",
  ].map(slotDefault),
  use_affordance: ([
    ["slot:place", "Place"],
    ["slot:open", "Open"],
    ["slot:eat", "Eat"],
    ["slot:drink", "Drink"],
    ["slot:equip", "Equip"],
    [
      "slot:fuel",
      "Fuel",
      "Item can be consumed as fuel or burned in a furnace, firepit, generator, or similar process.",
      ["burn"],
    ],
    ["slot:repair", "Repair"],
    ["slot:configure", "Configure"],
    ["slot:cast", "Cast", "Item can be cast from molten material or participates directly in casting.", ["cast metal"]],
    ["slot:fill", "Fill"],
    ["slot:empty", "Empty"],
    ["slot:preserve", "Preserve", "Item can preserve food or contents, or is directly involved in preserving."],
    ["slot:harvest", "Harvest"],
    ["slot:scan", "Scan"],
    ["slot:launch", "Launch", "Item can launch a vehicle or is directly used for launch."],
  ] satisfies Array<[string, string, string?, string[]?]>).map(defaultTuple),
};

export const FACET_POLICIES: Partial<Record<VocabularyFacetId, string>> = {
  activity: "Broad player activities. Prefer universal slot:* defaults. Reject recipe-internal verbs.",
  workflow: "Player-facing process/task contexts. Use recipe, guide, quest, or advancement evidence. Reject catch-alls and one-off tutorial/advancement titles.",
  workflow_role: "Scoped role values only, formatted as <workflow>#<role>. Parent must be an accepted workflow value.",
  used_at: "Player-facing station, machine, tool, or surface. Preserve raw recipe type evidence separately.",
  progression_stage: "Pack/mod progression gates, tiers, ages, voltages, dimensions. Conservative; reject item/product topics and one-off advancements.",
  organization_group: "Direct wall-home value. Accept only scarce, broad sections a human player would maintain primarily by item type/role, with use or state as secondary; not stations, recipe workflows, mod names, narrow material properties, or query filters.",
  mod_subsystem: "Identity-oriented mod subsystem. Do not assign from recipe participation alone.",
};

export const ROLE_TOKENS = ["input", "output"] as const;
export const ORGANIZATION_GROUP_PREFIX_STOP_TOKENS = new Set([
  "block",
  "blocks",
  "item",
  "items",
  "tag",
  "tags",
  "whitelisted",
  "blacklisted",
  "mineable",
  "needs",
  "incorrect",
  "replaceable",
  "replacements",
  "runtime",
  "generated",
  "compat",
  "completes",
]);

export const ORGANIZATION_GROUP_SUFFIX_STOP_TOKENS = new Set([
  "replaceable",
  "replaceables",
  "whitelisted",
  "blacklisted",
  "pickup",
  "tutorial",
]);
