package dev.imagio.slot.workflow.domain;

public enum ContextualSignalKind {
    CARRIED_SET_CHANGED,
    STATION_OPENED,
    STATION_CONTENTS_CHANGED,
    GOAL_CONTEXT_OBSERVED,
    RECIPE_CONTEXT_OBSERVED,
    ITEM_ACQUIRED,
    ITEM_TAKEN_FROM_STORAGE,
    ITEM_DEPOSITED_TO_STORAGE,
    ITEM_CRAFTED_OR_PRODUCED,
    ITEM_USED,
    ITEM_PLACED,
    ITEM_CONSUMED,
    ITEM_DAMAGED
}
